# Generated by Django 3.1 on 2020-09-13 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(2, 'Title must be greater then 2 characters')]),
        ),
    ]
